import * as fs from 'fs';
import * as path from 'path';
import { execFile } from 'child_process';
import { promisify } from 'util';
import type { Assumption, Plan, PlanStep } from '../types/index.js';

const execFileAsync = promisify(execFile);

export interface ExecContext {
  rootDir: string;
  workspaceDir: string;
  plan: Plan;
  assumptions: Assumption[];
  storyRaw: string;
}

function ensureParent(file: string): void {
  fs.mkdirSync(path.dirname(file), { recursive: true });
}

function abs(ctx: ExecContext, rel?: string): string {
  if (!rel) return ctx.workspaceDir;
  if (rel.startsWith('workspace/')) {
    return path.join(ctx.rootDir, rel);
  }
  return path.join(ctx.rootDir, rel);
}

function slugDir(ctx: ExecContext): string {
  const art = ctx.plan.steps.find((s) => s.artifact)?.artifact;
  if (art) {
    const parts = art.replace(/^workspace\//, '').split('/');
    return path.join(ctx.workspaceDir, parts[0]);
  }
  return path.join(ctx.workspaceDir, 'deliverable');
}

function storyExcerpt(ctx: ExecContext, n = 200): string {
  return ctx.storyRaw.replace(/\s+/g, ' ').trim().slice(0, n);
}

function writeAssumptionsMd(ctx: ExecContext, file: string): string {
  ensureParent(file);
  const lines = [
    '# Assumptions',
    '',
    `Story: ${storyExcerpt(ctx, 120)}`,
    '',
    'Fantasia filled gaps without asking clarifying questions:',
    '',
    ...ctx.assumptions.map((a) => `- **${a.id}**: ${a.text}  \n  _Rationale:_ ${a.rationale}`),
    '',
  ];
  fs.writeFileSync(file, lines.join('\n'), 'utf8');
  return `wrote ${file} (${ctx.assumptions.length} assumptions)`;
}

function deriveTodoItems(story: string): string[] {
  const base = [
    'Clarify goal in one sentence (self-authored)',
    'Identify primary artifact path',
    'Draft initial content',
    'Apply assumptions as constraints',
    'Self-review for completeness',
    'Mark verification criteria',
    'Record outcome for memory',
  ];
  // Pull quoted or capitalized phrases as extra items
  const extras = story
    .split(/[,.;]/)
    .map((x) => x.trim())
    .filter((x) => x.length > 8 && x.length < 60)
    .slice(0, 3)
    .map((x) => `Address: ${x}`);
  return [...base.slice(0, 5), ...extras, ...base.slice(5)].slice(0, 8);
}

function writeTodo(ctx: ExecContext, file: string, markDone: boolean): string {
  ensureParent(file);
  const items = deriveTodoItems(ctx.storyRaw);
  let content: string;
  if (!markDone && !fs.existsSync(file)) {
    content = [
      '# TODO',
      '',
      `Derived from: ${storyExcerpt(ctx)}`,
      '',
      ...items.map((it, i) => `- [ ] ${i + 1}. ${it}`),
      '',
    ].join('\n');
  } else {
    const existing = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : '';
    if (markDone) {
      content =
        existing
          .split('\n')
          .map((line) => line.replace(/^- \[ \] /, '- [x] '))
          .join('\n') +
        (existing.includes('## Done log')
          ? ''
          : `\n## Done log\n\nAll items marked done at ${new Date().toISOString()}.\n`);
    } else {
      content = existing || [
        '# TODO',
        '',
        ...items.map((it, i) => `- [ ] ${i + 1}. ${it}`),
        '',
      ].join('\n');
    }
  }
  fs.writeFileSync(file, content, 'utf8');
  return markDone ? `updated ${file} (all items done)` : `wrote ${file}`;
}

function writeReadme(ctx: ExecContext, file: string, fill: boolean): string {
  ensureParent(file);
  if (!fill || !fs.existsSync(file)) {
    const body = [
      `# ${path.basename(path.dirname(file))}`,
      '',
      '> Generated by Fantasia',
      '',
      '## Story',
      '',
      storyExcerpt(ctx, 300),
      '',
      '## Install',
      '',
      '```bash',
      'cd /workspace/fantasia && npm install',
      '```',
      '',
      '## Run',
      '',
      '```bash',
      'npm start',
      '# then paste a user story, or: npm run demo',
      '```',
      '',
      '## Assumptions',
      '',
      'See [assumptions.md](./assumptions.md).',
      '',
      fill ? '' : '_(stub — content pass pending)_',
      '',
    ];
    if (fill) {
      body.push('## Details', '', 'This deliverable was produced under Fantasia defaults:', '');
      for (const a of ctx.assumptions.slice(0, 5)) {
        body.push(`- ${a.text}`);
      }
      body.push('', '## Status', '', 'Complete (heuristic executor).', '');
    }
    fs.writeFileSync(file, body.join('\n'), 'utf8');
    return `wrote ${file}`;
  }
  // Fill pass: append details if missing
  let cur = fs.readFileSync(file, 'utf8');
  if (!cur.includes('## Details')) {
    cur +=
      '\n## Details\n\nExpanded from story and assumptions.\n\n' +
      ctx.assumptions.map((a) => `- ${a.id}: ${a.text}`).join('\n') +
      '\n';
    fs.writeFileSync(file, cur, 'utf8');
  }
  return `updated ${file}`;
}

function writeServer(ctx: ExecContext, file: string): string {
  ensureParent(file);
  const code = `#!/usr/bin/env node
/**
 * Minimal HTTP handler stub — Fantasia generated
 * Story: ${storyExcerpt(ctx, 80).replace(/\*\//g, '')}
 * Dry-run friendly: require() without listen when FANTASIA_DRY=1
 */
const http = require('http');

function handler(req, res) {
  res.writeHead(200, { 'Content-Type': 'application/json' });
  res.end(JSON.stringify({ ok: true, path: req.url, service: 'fantasia-stub' }));
}

function createServer() {
  return http.createServer(handler);
}

if (require.main === module && process.env.FANTASIA_DRY !== '1') {
  const port = process.env.PORT || 3911;
  createServer().listen(port, () => console.log('listening', port));
}

module.exports = { handler, createServer };
`;
  fs.writeFileSync(file, code, 'utf8');
  return `wrote ${file}`;
}

function writeSmoke(ctx: ExecContext, file: string): string {
  ensureParent(file);
  const serverRel = file.endsWith('.cjs') ? './server.cjs' : './server.js';
  const code = `#!/usr/bin/env node
process.env.FANTASIA_DRY = '1';
const { handler } = require('${serverRel}');
const { EventEmitter } = require('events');

function mockRes() {
  const e = new EventEmitter();
  e.status = 0;
  e.headers = {};
  e.body = '';
  e.writeHead = (s, h) => { e.status = s; e.headers = h; };
  e.end = (b) => { e.body = b; e.emit('end'); };
  return e;
}

const req = { url: '/health' };
const res = mockRes();
handler(req, res);
const parsed = JSON.parse(res.body);
if (!parsed.ok) { console.error('FAIL'); process.exit(1); }
console.log('SMOKE OK', parsed);
`;
  fs.writeFileSync(file, code, 'utf8');
  return `wrote ${file}`;
}

function writeTool(ctx: ExecContext, file: string): string {
  ensureParent(file);
  const code = `#!/usr/bin/env node
/**
 * Fantasia-generated CLI tool
 * ${storyExcerpt(ctx, 100).replace(/\*\//g, '')}
 */
const args = process.argv.slice(2);
if (args.includes('--help') || args.includes('-h')) {
  console.log('Usage: tool.js [--help] [--dry]');
  console.log('Fantasia heuristic tool — processes the canned story context.');
  process.exit(0);
}
console.log('tool: running');
console.log('story:', ${JSON.stringify(storyExcerpt(ctx, 80))});
if (args.includes('--dry')) {
  console.log('dry-run: no side effects');
} else {
  console.log('done');
}
`;
  fs.writeFileSync(file, code, 'utf8');
  try {
    fs.chmodSync(file, 0o755);
  } catch {
    /* ignore */
  }
  return `wrote ${file}`;
}

function writeMain(ctx: ExecContext, file: string): string {
  ensureParent(file);
  const code = `#!/usr/bin/env node
// Fantasia deliverable for: ${storyExcerpt(ctx, 80).replace(/\*\//g, '')}
console.log('Fantasia deliverable');
console.log(${JSON.stringify(storyExcerpt(ctx, 120))});
console.log('status: ok');
`;
  fs.writeFileSync(file, code, 'utf8');
  return `wrote ${file}`;
}

function writeHtml(ctx: ExecContext, file: string, withJs: boolean): string {
  ensureParent(file);
  const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<title>Fantasia</title>
<style>
  html,body{background:#000;color:#0f0;font-family:ui-monospace,monospace;margin:0;padding:1.5rem;}
  h1{font-weight:normal;border-bottom:1px solid #0f0;padding-bottom:.5rem;}
  .tty{border:1px solid #0f0;padding:1rem;max-width:40rem;}
  button{background:#000;color:#0f0;border:1px solid #0f0;padding:.4rem .8rem;font-family:inherit;cursor:pointer;}
  button:hover{background:#0f0;color:#000;}
</style>
</head>
<body>
  <h1>$ fantasia ui</h1>
  <div class="tty">
    <p>Story: ${storyExcerpt(ctx, 160).replace(/</g, '&lt;')}</p>
    <p id="out">ready.</p>
    <button type="button" id="go">run</button>
  </div>
  ${
    withJs
      ? `<script>
  document.getElementById('go').onclick = function(){
    document.getElementById('out').textContent = 'completed @ ' + new Date().toISOString();
  };
</script>`
      : ''
  }
</body>
</html>
`;
  fs.writeFileSync(file, html, 'utf8');
  return `wrote ${file}`;
}

function writeVerification(ctx: ExecContext, file: string, mid: boolean): string {
  ensureParent(file);
  const dir = slugDir(ctx);
  const expected = ctx.plan.steps
    .filter((s) => s.artifact && s.kind !== 'verify' && s.kind !== 'reflect')
    .map((s) => s.artifact!)
    .filter((a, i, arr) => arr.indexOf(a) === i);

  const results: { path: string; ok: boolean }[] = [];
  for (const rel of expected) {
    const p = abs(ctx, rel);
    results.push({ path: rel, ok: fs.existsSync(p) });
  }
  // Also check dir exists
  results.push({ path: dir.replace(ctx.rootDir + '/', ''), ok: fs.existsSync(dir) });

  const allOk = results.every((r) => r.ok);
  const lines = [
    mid ? '# Mid-run Self-Check' : '# Verification Report',
    '',
    `plan: ${ctx.plan.id}`,
    `time: ${new Date().toISOString()}`,
    `result: ${allOk ? 'PASS' : 'FAIL'}`,
    '',
    '## Checks',
    '',
    ...results.map((r) => `- [${r.ok ? 'x' : ' '}] ${r.path}`),
    '',
    '## Notes',
    '',
    mid
      ? 'Lesson-driven mid-check: confirming artifacts before final verify.'
      : 'Final verification produced by Fantasia local executor.',
    '',
  ];
  fs.writeFileSync(file, lines.join('\n'), 'utf8');
  if (!allOk && !mid) {
    throw new Error(`verification failed: missing ${results.filter((r) => !r.ok).map((r) => r.path).join(', ')}`);
  }
  return `${allOk ? 'PASS' : 'PARTIAL'} → ${file}`;
}

async function runShell(ctx: ExecContext, file: string): Promise<string> {
  const p = abs(ctx, file);
  if (!fs.existsSync(p)) {
    throw new Error(`shell target missing: ${file}`);
  }
  const { stdout, stderr } = await execFileAsync(process.execPath, [p], {
    cwd: path.dirname(p),
    timeout: 15000,
    env: { ...process.env, FANTASIA_DRY: '1' },
  });
  const out = (stdout || '').trim() || (stderr || '').trim() || '(no output)';
  return `ran ${file}: ${out.split('\n')[0]}`;
}

/**
 * Local heuristic executor — writes real artifacts, no API keys.
 */
export async function executeLocal(ctx: ExecContext, step: PlanStep): Promise<string> {
  const file = step.artifact ? abs(ctx, step.artifact) : '';

  switch (step.kind) {
    case 'analyze':
      return `recorded domain analysis for plan ${ctx.plan.id}`;

    case 'create':
    case 'modify': {
      const title = step.title.toLowerCase();
      const art = (step.artifact || '').toLowerCase();

      if (art.endsWith('assumptions.md') || title.includes('assumption')) {
        return writeAssumptionsMd(ctx, file);
      }
      if (art.endsWith('todo.md') || title.includes('checklist') || title.includes('todo')) {
        return writeTodo(ctx, file, title.includes('execute') || title.includes('mark') || title.includes('completion'));
      }
      if (art.endsWith('readme.md') || title.includes('readme')) {
        return writeReadme(ctx, file, title.includes('fill') || title.includes('content') || title.includes('companion'));
      }
      if (art.endsWith('server.js') || art.endsWith('server.cjs') || title.includes('handler') || title.includes('scaffold handler')) {
        return writeServer(ctx, file);
      }
      if (art.endsWith('smoke.js') || art.endsWith('smoke.cjs') || title.includes('smoke script')) {
        return writeSmoke(ctx, file);
      }
      if (art.endsWith('tool.js') || art.endsWith('tool.cjs') || (title.includes('script') && (art.endsWith('.js') || art.endsWith('.cjs')))) {
        return writeTool(ctx, file);
      }
      if (art.endsWith('main.js') || art.endsWith('main.cjs')) {
        return writeMain(ctx, file);
      }
      if (art.endsWith('index.html') || title.includes('html')) {
        return writeHtml(ctx, file, title.includes('interactivity') || title.includes('js'));
      }
      if (art.endsWith('before.md')) {
        ensureParent(file);
        fs.writeFileSync(
          file,
          `# Before\n\n${storyExcerpt(ctx)}\n\nIssues noted:\n- Vague scope\n- No structure\n- Missing verification\n`,
          'utf8'
        );
        return `wrote ${file}`;
      }
      if (art.endsWith('after.md')) {
        ensureParent(file);
        fs.writeFileSync(
          file,
          `# After\n\nImproved structure for: ${storyExcerpt(ctx)}\n\n- Clear sections\n- Assumptions logged\n- Ready for verify\n`,
          'utf8'
        );
        return `wrote ${file}`;
      }
      if (art.endsWith('summary.md')) {
        ensureParent(file);
        fs.writeFileSync(
          file,
          `# Summary\n\nBefore → After refactor complete.\nAssumptions applied: ${ctx.assumptions.length}\n`,
          'utf8'
        );
        return `wrote ${file}`;
      }
      if (art.endsWith('testplan.md')) {
        ensureParent(file);
        fs.writeFileSync(
          file,
          `# Test Plan\n\n1. Artifact exists\n2. Script exits 0\n3. Memory updated\n\nStory: ${storyExcerpt(ctx)}\n`,
          'utf8'
        );
        return `wrote ${file}`;
      }
      if (art.endsWith('assert.js') || art.endsWith('assert.cjs')) {
        ensureParent(file);
        fs.writeFileSync(
          file,
          `#!/usr/bin/env node\nconst fs=require('fs');const path=require('path');\nconst ok=fs.existsSync(path.join(__dirname,'TESTPLAN.md'));\nif(!ok){console.error('FAIL');process.exit(1);}\nconsole.log('ASSERT OK');\n`,
          'utf8'
        );
        return `wrote ${file}`;
      }
      if (art.endsWith('progress.md') || art.endsWith('midcheck.md')) {
        ensureParent(file);
        fs.writeFileSync(
          file,
          `# Progress\n\nCheckpoint at ${new Date().toISOString()}\nPlan: ${ctx.plan.id}\n`,
          'utf8'
        );
        return `wrote ${file}`;
      }
      // Generic create
      ensureParent(file);
      fs.writeFileSync(file, `# ${step.title}\n\n${step.action}\n\n${storyExcerpt(ctx)}\n`, 'utf8');
      return `wrote ${file}`;
    }

    case 'shell':
      return runShell(ctx, step.artifact || '');

    case 'verify':
      return writeVerification(ctx, file, /mid/i.test(step.title));

    case 'reflect':
      return 'reflection handed to engine';

    default:
      return `noop ${step.kind}`;
  }
}
